# GitHub Actions workflow
# https://help.github.com/actions

name: Push (main)

on:
  push:
    branches: [main]

env:
  VERSION: ${{ github.event.pull_request.number }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      # Authenticate Google Cloud SDK
      - name: gcloud auth activate-service-account
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 --decode > "$GOOGLE_APPLICATION_CREDENTIALS"
          gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"

      # Install dependencies
      - run: yarn install

      # Deploy
      - run: yarn tsc --build
      - run: yarn site:deploy --env=test
      - run: yarn api:deploy --env=test
      - run: yarn app:deploy
      - run: yarn admin:deploy
